---
- name: Web-page Hosting
  hosts: servers
  become: true
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: latest

    - name: Create backup of default NGINX configuration file
      command: cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
      args:
        creates: /etc/nginx/nginx.conf.bak

    - name: Configure NGINX to serve webpage
      copy:
        src: index.html
        dest: /var/www/html
